onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/clk}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/clk}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/rst}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/en_data}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/en_data}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/en_sum}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/en_sum}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/en}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/en}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/a}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/a}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/loopbuf_out}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/loopbuf_out}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/s_axis_sum_tuser}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/s_axis_sum_tuser}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/vin}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/vin}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/s_axis_data/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/s_axis_data/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/s_axis_data/tready}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/s_axis_data/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/s_axis_data/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/s_axis_data/tready}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/din}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/din}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/s_axis_loopbuf/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/s_axis_loopbuf/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/s_axis_loopbuf/tready}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/loopbuf/s_axis/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/loopbuf/s_axis/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/loopbuf/s_axis/tready}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/sin}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/sin}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/s_axis_sum/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/s_axis_sum/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/s_axis_sum/tready}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/s_axis_sum/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/s_axis_sum/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/s_axis_sum/tready}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/m_axis_data/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/m_axis_data/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/m_axis_data/tready}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/m_axis_data/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/m_axis_data/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/m_axis_data/tready}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/m_axis_sum/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/m_axis_sum/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/m_axis_sum/tready}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/m_axis_sum/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/m_axis_sum/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/m_axis_sum/tready}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/h}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/h}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2785500 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 351
configure wave -valuecolwidth 69
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {2428891 ps} {2879413 ps}
