onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /xpm_ospfb_tb/adc_clk
add wave -noupdate /xpm_ospfb_tb/dsp_clk
add wave -noupdate /xpm_ospfb_tb/rst
add wave -noupdate /xpm_ospfb_tb/en
add wave -noupdate /xpm_ospfb_tb/DUT/s_axis_ospfb/tdata
add wave -noupdate /xpm_ospfb_tb/DUT/s_axis_ospfb/tvalid
add wave -noupdate /xpm_ospfb_tb/DUT/s_axis_ospfb/tready
add wave -noupdate /xpm_ospfb_tb/DUT/ospfb_inst/hold_rst
add wave -noupdate /xpm_ospfb_tb/DUT/ospfb_inst/ns
add wave -noupdate /xpm_ospfb_tb/DUT/ospfb_inst/cs
add wave -noupdate /xpm_ospfb_tb/DUT/ospfb_inst/din_im
add wave -noupdate /xpm_ospfb_tb/DUT/ospfb_inst/pc_in_im
add wave -noupdate /xpm_ospfb_tb/DUT/ospfb_inst/fir_im/s_axis/tdata
add wave -noupdate /xpm_ospfb_tb/DUT/ospfb_inst/fir_im/s_axis/tvalid
add wave -noupdate /xpm_ospfb_tb/DUT/ospfb_inst/fir_im/s_axis/tready
add wave -noupdate /xpm_ospfb_tb/DUT/ospfb_inst/s_axis_tuser
add wave -noupdate /xpm_ospfb_tb/DUT/ospfb_inst/fir_im/m_axis/tdata
add wave -noupdate /xpm_ospfb_tb/DUT/ospfb_inst/fir_im/m_axis/tvalid
add wave -noupdate /xpm_ospfb_tb/DUT/ospfb_inst/fir_im/m_axis/tready
add wave -noupdate /xpm_ospfb_tb/DUT/ospfb_inst/m_axis_tuser_im
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/h}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_data[0]/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_data[0]/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_data[0]/tready}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/h}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_data[1]/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_data[1]/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_data[1]/tready}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/loopbuf/ns}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/loopbuf/cs}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/loopbuf/new_sample}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/a}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/loopbuf/s_axis/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/loopbuf/s_axis/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/loopbuf/s_axis/tready}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/s_axis_sum_tuser}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/databuf/ns}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/databuf/cs}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[0]/pe/databuf/new_sample}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/gen_pe[1]/pe/s_axis_sum_tuser}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_data[2]/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_data[2]/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_data[2]/tready}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_sum[0]/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_sum[0]/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_sum[0]/tready}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_sum[1]/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_sum[1]/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_sum[1]/tready}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_sum[2]/tdata}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_sum[2]/tvalid}
add wave -noupdate {/xpm_ospfb_tb/DUT/ospfb_inst/fir_im/axis_pe_sum[2]/tready}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2771390 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 352
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {2504661 ps} {2964300 ps}
